name: chatingbot
description: chatingBot is a powerful fully customizable chatbot you can add to your flutter project for all plaftorms
version: 1.0.5
homepage: https://myiketech.blogspot.com
repository: https://github.com/Aquarius-blake/chatbotB

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mailer: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - lib/assets/

